### ISSUE TITLE
Retrieval example

### ISSUE THREAD

**Issue by silverberrydesert** [Dataherald/Assistant#1]
Thank you for your excellent work. If it's not too much trouble, are you able to add an example for using retrieval with this library?

**Comment by MohammadrezaPourreza** [comment]
Hi, thank you for your kind words, I added an example of the retrieval assistant, here: https://github.com/Dataherald/Assistant/blob/main/retrieval_assistant.py

**Comment by silverberrydesert** [comment]
Wow thank you! Much appreciated.
